### ISSUE TITLE
toRandFile doesn't seem to "work"

### ISSUE THREAD

**Issue by bluuman** [alexandernst/memory-dumper#13]
I have successfully built memory-dumper and all plugins except for zwf plugin (couldn't find updated lzma lib, but don't need it anyway). I run the memory dumper targeting my firefox, I get console output of successful matches, however, nothing it put in the ./dumps/ folder as it should.

https://github.com/alexandernst/memory-dumper/blob/master/plugins/png.cpp#L182

**Comment by alexandernst** [comment]
Hmm, that is weird. Does the app segfault or something? Or does it just doesn't create the file? Do you have the 'dumps' folder? (the dumps folder isn't created if it doesn't exist)

**Comment by jalius** [comment]
The program seems to complete normally, and prints out successful matches. The dumps folder exists at on directory up from the exe.

**Comment by alexandernst** [comment]
The dump folder should be in the same folder where the binary is.

**Comment by jalius** [comment]
Thanks! Creating a dumps folder where the binary is fixed my issue. Everything seems to be working great :+1:
